name: Build and deploy Zola site

on:
  push:
    branches:
      - main  # adjust this if your default branch has a different name

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Build and deploy Zola site
        uses: shalzz/zola-deploy-action@v0.20.0
        env:
          PAGES_BRANCH: gh-pages
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOMAIN: rdelaf.nand.cl 